server:
  http_listen_port: 9080
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: portal
    static_configs:
      - targets: [localhost]
        labels:
          job: portal
          service: gateway
          __path__: /var/log/app/gateway.log
      - targets: [localhost]
        labels:
          job: portal
          service: analise
          __path__: /var/log/app/analise.log
      - targets: [localhost]
        labels:
          job: portal
          service: store
          __path__: /var/log/app/store.log
