services:
  mongo1:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo2:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo3:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo-init:
    image: mongo:7
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    restart: "no"
    entrypoint: >
      bash -c "
      mongosh --host mongo1:27017 --eval \"
        try {
          rs.status();
          print('replica set já iniciado');
        } catch (e) {
          rs.initiate({
            _id: 'rs0',
            members: [
              { _id: 0, host: 'mongo1:27017' },
              { _id: 1, host: 'mongo2:27017' },
              { _id: 2, host: 'mongo3:27017' }
            ]
          });
          print('replica set iniciado');
        }
      \"
      "

  api:
    build: ./api
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
    ports:
      - "8083:8000"
    depends_on:
      mongo-init:
        condition: service_completed_successfully

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
